import {FormEvent,useCallback,useState} from 'react';
import {Alert,Box,Button,Checkbox,CircularProgress,Container,FormControlLabel,Grid,Link as MuiLink,MenuItem,TextField,Typography} from '@mui/material';
import {Link} from 'react-router-dom';
import Recaptcha from '../Recaptcha';import {usePrivacy} from '../../privacy/PrivacyContext';import {appendLocation,namePattern,normalizePhone,phonePattern,sendContact} from '../../utils/contactForm';

export default function DynamicQuoteForm({title}:{title:string}){
  const[status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');const[error,setError]=useState('');const[token,setToken]=useState('');const[resetKey,setResetKey]=useState(0);const{location}=usePrivacy();const captchaChanged=useCallback((value:string)=>setToken(value),[]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;if(!token){setError('Confirme o reCAPTCHA antes de enviar.');setStatus('error');return}setStatus('sending');setError('');try{const body=new FormData(form);body.set('assunto','Novo contato pelo site InfoService');body.set('telefone',normalizePhone(String(body.get('telefone')??'')));body.append('recaptchaToken',token);appendLocation(body,location);await sendContact(body);form.reset();setStatus('success');setResetKey(value=>value+1)}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível enviar a mensagem.');setStatus('error');setResetKey(value=>value+1)}};
  return <Box id="contato" component="section" sx={{py:{xs:9,md:13},bgcolor:'#f6f7f9',borderTop:'1px solid #e0e0e0'}}><Container><Grid container spacing={7}><Grid item xs={12} md={6}><Typography variant="overline" color="#d81159" fontWeight={800}>FALE COM A INFOSERVICE</Typography><Typography variant="h2" sx={{mt:2}}>{title}</Typography><Typography mt={3} color="text.secondary">Conte-nos um pouco sobre o seu contexto. Nossa equipe entrará em contato para uma conversa inicial.</Typography></Grid><Grid item xs={12} md={6}><Box component="form" onSubmit={submit} noValidate><Grid container spacing={2}>
    <Grid item xs={12} sm={6}><TextField required fullWidth name="nome" label="Nome completo" autoComplete="name" inputProps={{minLength:5,maxLength:120,pattern:namePattern.source}} helperText="Informe nome e sobrenome."/></Grid>
    <Grid item xs={12} sm={6}><TextField required fullWidth name="email" type="email" label="E-mail institucional" autoComplete="email" inputProps={{maxLength:254}}/></Grid>
    <Grid item xs={12} sm={6}><TextField required fullWidth name="instituicao" label="Instituição" inputProps={{minLength:2,maxLength:160}}/></Grid>
    <Grid item xs={12} sm={6}><TextField required fullWidth name="telefone" type="tel" label="Telefone - WhatsApp" autoComplete="tel" inputProps={{inputMode:'tel',pattern:phonePattern.source,minLength:10,maxLength:20}}/></Grid>
    <Grid item xs={12}><TextField select fullWidth name="perfil" label="Perfil" defaultValue=""><MenuItem value="Gestão pública">Gestão pública</MenuItem><MenuItem value="Saúde privada">Saúde privada</MenuItem><MenuItem value="Pesquisa e inovação">Pesquisa e inovação</MenuItem></TextField></Grid>
    <Grid item xs={12}><TextField required fullWidth name="mensagem" multiline rows={4} label="Qual desafio deseja resolver?" inputProps={{minLength:10,maxLength:4000}}/></Grid>
    <Box component="input" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" sx={{position:'absolute',left:'-10000px',width:1,height:1}}/>
    <Grid item xs={12}><FormControlLabel required control={<Checkbox required name="privacidade" value="aceito"/>} label={<Typography variant="body2">Li e concordo com a <MuiLink component={Link} to="/privacidade">Política de Privacidade e DPO</MuiLink>.</Typography>}/></Grid>
    <Grid item xs={12}><Recaptcha onChange={captchaChanged} resetKey={resetKey}/></Grid>
    <Grid item xs={12}><Button disabled={status==='sending'} type="submit" variant="contained" size="large" startIcon={status==='sending'?<CircularProgress size={18}/>:undefined}>{status==='sending'?'Enviando...':'Solicitar apresentação'}</Button></Grid>
    {status==='success'&&<Grid item xs={12}><Alert severity="success" onClose={()=>setStatus('idle')}>Mensagem enviada com sucesso, em breve nossa equipe entrará em contato</Alert></Grid>}{status==='error'&&<Grid item xs={12}><Alert severity="error" onClose={()=>setStatus('idle')}>{error}</Alert></Grid>}
  </Grid></Box></Grid></Grid></Container></Box>
}
