import {ArrowForward,AutoGraphOutlined,CheckCircleOutline,HubOutlined,InsightsOutlined,LanOutlined,SecurityOutlined,SyncAltOutlined} from '@mui/icons-material';
import {Box,Button,Container,Grid,Stack,Typography} from '@mui/material';
import {Link} from 'react-router-dom';
import SectionTag from '../components/SectionTag';

const challenges=['Consultar diferentes plataformas para compreender o mesmo cenário','Solicitar informações a vários setores e aguardar a consolidação','Exportar relatórios e manter planilhas paralelas','Reconciliar indicadores que chegam com conceitos ou períodos diferentes'];
const journey=[['01','Prioridade','Selecionamos uma necessidade concreta da instituição.'],['02','Conexão','Integramos somente as fontes necessárias para esse contexto.'],['03','Validação','Acompanhamos indicadores definidos em conjunto.'],['04','Evolução','A ampliação ocorre por etapas, conforme a estratégia institucional.']];
const valueDimensions=[[<SyncAltOutlined/>,'Operação','Menor esforço para localizar, reunir e reconciliar informações.'],[<InsightsOutlined/>,'Gestão','Indicadores organizados para uma leitura mais coordenada do cenário.'],[<AutoGraphOutlined/>,'Planejamento','Identificação mais ágil de tendências, riscos e necessidades.'],[<HubOutlined/>,'Integração','Aproveitamento dos sistemas e dados que a instituição já possui.'],[<SecurityOutlined/>,'Governança','Mais rastreabilidade, padronização e controle sobre o uso dos dados.'],[<LanOutlined/>,'Continuidade','Evolução progressiva, preservando processos que continuam relevantes.']] as const;
const indicators=['tempo necessário para consolidar informações','quantidade de fontes consultadas pela gestão','recorrência de divergências entre indicadores','atualização e disponibilidade dos dados','volume de atividades manuais e planilhas paralelas','qualidade, completude e rastreabilidade das informações'];

export default function ClusterHDI(){return <>
  <Box component="section" sx={{bgcolor:'#0b1728',color:'white',py:{xs:9,md:14},position:'relative',overflow:'hidden'}}>
    <Box sx={{position:'absolute',width:460,height:460,border:'1px solid rgba(0,213,242,.18)',borderRadius:'50%',right:-110,top:-180}}/><Box sx={{position:'absolute',width:290,height:290,border:'1px solid rgba(216,17,89,.22)',borderRadius:'50%',right:80,bottom:-190}}/>
    <Container><Grid container spacing={7} alignItems="center"><Grid item xs={12} md={7}><SectionTag color="#00d5f2">CLUSTER HDI</SectionTag><Typography variant="h1" sx={{mt:2,maxWidth:820,fontSize:{xs:'2.7rem',md:'4.4rem'}}}>Seus sistemas continuam operando. Seus dados passam a trabalhar juntos.</Typography><Typography sx={{mt:3,fontSize:{xs:17,md:19},lineHeight:1.65,color:'#dce5ef',maxWidth:750}}>O HDI cria uma camada de integração, governança e inteligência sobre o ambiente existente, sem exigir que a instituição substitua todos os seus sistemas ou interrompa a rotina para começar.</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={2} mt={4}><Button component="a" href="#modelo" variant="contained" endIcon={<ArrowForward/>}>Conheça o modelo</Button><Button component={Link} to="/contato?assunto=integracao" variant="outlined" sx={{color:'white',borderColor:'#718197'}}>Conversar sobre integração</Button></Stack></Grid><Grid item xs={12} md={5}><Box sx={{border:'1px solid rgba(255,255,255,.16)',p:{xs:3,md:4},bgcolor:'rgba(255,255,255,.035)'}}><Typography variant="overline" sx={{color:'#00d5f2',fontWeight:800,letterSpacing:2}}>PRINCÍPIO DE IMPLANTAÇÃO</Typography><Typography variant="h4" sx={{mt:2,fontWeight:800}}>Preservar. Conectar. Evoluir.</Typography><Typography sx={{mt:2,color:'#c7d2df',lineHeight:1.7}}>A transformação acontece por etapas, a partir de necessidades reais e com a instituição no controle das decisões.</Typography></Box></Grid></Grid></Container>
  </Box>
  <Box component="section" sx={{py:{xs:8,md:12}}}><Container><Grid container spacing={8}><Grid item xs={12} md={5}><SectionTag>A REALIDADE DAS INSTITUIÇÕES</SectionTag><Typography variant="h2" sx={{mt:2}}>O problema nem sempre é a falta de sistemas.</Typography><Typography sx={{mt:3,color:'text.secondary',fontSize:17,lineHeight:1.75}}>Ao longo do tempo, cada solução passou a cumprir uma função importante. O desafio surge quando as informações permanecem distribuídas e a gestão precisa reconstruir a visão completa a cada decisão.</Typography></Grid><Grid item xs={12} md={7}><Stack sx={{borderTop:'1px solid #d9e0e8'}}>{challenges.map((item,index)=><Stack key={item} direction="row" spacing={2.5} sx={{py:2.5,borderBottom:'1px solid #d9e0e8',alignItems:'flex-start'}}><Typography sx={{color:'secondary.main',fontWeight:900}}>0{index+1}</Typography><Typography sx={{fontSize:{xs:16,md:18},fontWeight:650}}>{item}</Typography></Stack>)}</Stack></Grid></Grid></Container></Box>
  <Box id="modelo" component="section" sx={{py:{xs:8,md:12},bgcolor:'#f4f7fa'}}><Container><Box maxWidth={800}><SectionTag>INTEGRAÇÃO SEM RUPTURA</SectionTag><Typography variant="h2" sx={{mt:2}}>Uma evolução gradual, orientada por prioridades.</Typography><Typography sx={{mt:3,color:'text.secondary',fontSize:17,lineHeight:1.75}}>O HDI não precisa começar por toda a instituição. O primeiro passo pode ser uma unidade, uma linha de cuidado ou um conjunto restrito de indicadores.</Typography></Box><Grid container spacing={2} sx={{mt:5}}>{journey.map(([number,title,description])=><Grid item xs={12} sm={6} md={3} key={number}><Box sx={{height:'100%',bgcolor:'white',p:3.5,borderTop:'4px solid #00b4d8'}}><Typography sx={{fontSize:13,fontWeight:900,color:'secondary.main',letterSpacing:1.5}}>{number}</Typography><Typography variant="h5" sx={{mt:2,fontWeight:800}}>{title}</Typography><Typography sx={{mt:1.5,color:'text.secondary',lineHeight:1.65}}>{description}</Typography></Box></Grid>)}</Grid></Container></Box>
  <Box component="section" sx={{py:{xs:8,md:12}}}><Container><Box maxWidth={820}><SectionTag>VALOR PERCEBIDO</SectionTag><Typography variant="h2" sx={{mt:2}}>O que muda quando os dados passam a trabalhar de forma coordenada.</Typography></Box><Grid container spacing={3} sx={{mt:4}}>{valueDimensions.map(([icon,title,description])=><Grid item xs={12} sm={6} md={4} key={title}><Box sx={{height:'100%',p:3.5,border:'1px solid #dce3ea','& svg':{fontSize:34,color:'primary.main'}}}>{icon}<Typography variant="h5" sx={{mt:2,fontWeight:800}}>{title}</Typography><Typography sx={{mt:1.5,color:'text.secondary',lineHeight:1.65}}>{description}</Typography></Box></Grid>)}</Grid></Container></Box>
  <Box component="section" sx={{py:{xs:8,md:12},bgcolor:'#101828',color:'white'}}><Container><Grid container spacing={8}><Grid item xs={12} md={5}><SectionTag color="#00d5f2">AVALIAÇÃO RESPONSÁVEL</SectionTag><Typography variant="h2" sx={{mt:2}}>Resultados acompanhados com critérios definidos em conjunto.</Typography><Typography sx={{mt:3,color:'#c7d2df',lineHeight:1.75}}>Antes de ampliar uma implantação, a instituição pode estabelecer uma linha de base e acompanhar a evolução dos aspectos relevantes para seu contexto.</Typography></Grid><Grid item xs={12} md={7}><Grid container spacing={2}>{indicators.map(item=><Grid item xs={12} sm={6} key={item}><Stack direction="row" spacing={1.5} sx={{p:2.2,bgcolor:'rgba(255,255,255,.05)',height:'100%'}}><CheckCircleOutline sx={{color:'#00d5f2',mt:.2}}/><Typography sx={{lineHeight:1.55}}>{item}</Typography></Stack></Grid>)}</Grid><Typography sx={{mt:3,fontSize:13,color:'#9eabba',lineHeight:1.6}}>Os indicadores são definidos conforme as prioridades de cada instituição. O HDI apoia a análise e não substitui decisões clínicas, assistenciais ou gerenciais.</Typography></Grid></Grid></Container></Box>
  <Box component="section" sx={{py:{xs:8,md:11},textAlign:'center'}}><Container maxWidth="md"><Typography variant="h2">Não se trata de trocar tudo.</Typography><Typography variant="h2" sx={{color:'primary.main'}}>Trata-se de fazer o que já existe trabalhar de forma coordenada.</Typography><Typography sx={{mt:3,color:'text.secondary',fontSize:17,lineHeight:1.7}}>Preservamos o que funciona, conectamos o que está disperso e evoluímos com resultados verificáveis.</Typography><Button component={Link} to="/contato?assunto=integracao" variant="contained" endIcon={<ArrowForward/>} sx={{mt:4}}>Planejar uma integração gradual</Button></Container></Box>
</>}
