import {ArrowForward} from '@mui/icons-material';
import {Box,Button,Container,Typography} from '@mui/material';
import {Link} from 'react-router-dom';
import HeroSection from '../components/sections/HeroSection';
import TechnicalMatrix from '../components/sections/TechnicalMatrix';

const items=[['LGPD','Privacidade, finalidade, minimização e direitos dos titulares incorporados à plataforma.'],['Segurança da informação','Criptografia, segregação, monitoramento e resposta a incidentes.'],['Anonimização de prontuários','Pseudonimização e proteção de informações clínicas sensíveis.'],['Regulação setorial','Controles alinhados às exigências aplicáveis ao setor da saúde.'],['Auditoria fim-a-fim','Registro completo das transformações e dos acessos realizados.'],['Governança de acesso','Menor privilégio, perfis de acesso e revisões periódicas.']].map(([title,description])=>({title,description}));

export default function Governanca(){return <><HeroSection compact tag="GOVERNANÇA & COMPLIANCE" title="Segurança e conformidade não são funcionalidades — são fundação."/><Box sx={{py:{xs:9,md:13}}}><Container><TechnicalMatrix items={items} checks/></Container></Box><Box sx={{py:{xs:7,md:9},bgcolor:'#101828',color:'white'}}><Container><Box maxWidth={820}><Typography variant="overline" sx={{color:'#00d5f2',fontWeight:800,letterSpacing:2}}>GOVERNANÇA COM PROPÓSITO</Typography><Typography variant="h2" sx={{mt:2}}>Integração não precisa significar ruptura.</Typography><Typography sx={{mt:2.5,color:'#c7d2df',fontSize:17,lineHeight:1.7}}>Conheça como o HDI conecta sistemas existentes, preserva processos relevantes e permite uma evolução gradual, com rastreabilidade e controle institucional.</Typography><Button component={Link} to="/cluster-hdi" variant="contained" endIcon={<ArrowForward/>} sx={{mt:3}}>Conhecer o Cluster HDI</Button></Box></Container></Box></>}
