import {Box,Container,Divider,Link,Stack,Typography} from '@mui/material';
import {useLanguage,type Language} from '../i18n/LanguageContext';

type Copy={eyebrow:string;title:string;intro:string;updated:string;sections:[string,string][];dpo:[string,string,string,string];closing:string};
const email='mauroslucios@infoservicetechnology.com.br';
const copies:Record<Language,Copy>={
'pt-BR':{eyebrow:'PRIVACIDADE E GOVERNANÇA',title:'Política de Privacidade',intro:'Informações sobre o tratamento de dados pessoais no site da InfoService Technology e canal de atendimento do Encarregado.',updated:'Última atualização: 20 de agosto de 2026.',sections:[
['1. Quem trata os dados','A InfoService Technology é responsável pelo tratamento dos dados enviados voluntariamente pelos visitantes por meio deste site e dos formulários de contato. Em projetos contratados, o papel de controlador ou operador será definido no instrumento aplicável e nas instruções do cliente.'],
['2. Dados coletados e finalidades','Podemos receber nome, e-mail, empresa ou instituição, WhatsApp, assunto e mensagem. Esses dados são utilizados para responder solicitações, preparar contatos institucionais, prestar informações sobre as soluções e manter registros de atendimento e segurança.'],
['3. Consentimento e base legal','O envio do formulário depende da leitura e aceitação desta Política. O consentimento pode ser revogado sem afetar tratamentos anteriores. Conforme o contexto, também podem ser aplicadas as bases legais de medidas pré-contratuais, obrigação legal, exercício de direitos e legítimo interesse.'],
['4. Cookies','O site utiliza um cookie necessário e armazenamento local para lembrar a preferência do aviso de cookies. Os formulários carregam o Google reCAPTCHA v2, que pode usar o cookie técnico _GRECAPTCHA para análise de risco. Não são ativados cookies opcionais de publicidade ou análise comportamental.'],
['5. Localização aproximada','Após a aceitação de cookies opcionais, o formulário pode solicitar, de forma facultativa, a localização aproximada pelo navegador. Se a autorização for recusada ou indisponível, o atendimento continua sem coordenadas.'],
['6. Compartilhamento e fornecedores técnicos','Utilizamos o FormSubmit para processar e encaminhar mensagens ao e-mail institucional da InfoService. Os formulários também utilizam o Google reCAPTCHA v2 para reduzir envios automatizados. A chave secreta não é exposta no navegador.'],
['7. Segurança e retenção','Aplicamos validação de campos, honeypot anti-spam, reCAPTCHA v2, proteção padrão do FormSubmit e transmissão HTTPS. As informações são mantidas pelo tempo necessário ao atendimento ou pelos prazos legais e contratuais aplicáveis, sendo depois eliminadas ou anonimizadas quando possível.'],
['8. Direitos do titular','O titular pode solicitar confirmação, acesso, correção, anonimização, bloqueio, eliminação, portabilidade quando cabível, informações sobre compartilhamentos e revisão de decisões automatizadas relevantes. A solicitação pode exigir confirmação de identidade e encaminhamento ao controlador responsável.']],dpo:['9. Encarregado pelo tratamento de dados (DPO)','Para dúvidas e solicitações sobre proteção de dados, envie uma mensagem para ',' com o assunto “Privacidade e DPO”.','As solicitações serão respondidas dentro dos prazos legais aplicáveis, observados os requisitos de segurança, sigilo e a eventual atuação de outro controlador.'],closing:'Esta política pode ser atualizada para refletir mudanças legais, técnicas ou operacionais. A versão vigente estará sempre disponível nesta página.'},
en:{eyebrow:'PRIVACY AND GOVERNANCE',title:'Privacy Policy',intro:'Information about personal data processing on the InfoService Technology website and how to contact the Data Protection Officer.',updated:'Last updated: August 20, 2026.',sections:[
['1. Who processes the data','InfoService Technology processes data voluntarily submitted through this website and its contact forms. In contracted projects, the controller or processor role is defined by the applicable agreement and the client’s instructions.'],
['2. Data collected and purposes','We may receive your name, email, company or institution, WhatsApp number, subject and message. We use this data to answer requests, arrange institutional contacts, provide information about our solutions, and maintain service and security records.'],
['3. Consent and legal basis','Submitting a form requires reading and accepting this Policy. Consent may be withdrawn without affecting prior processing. Depending on the context, processing may also rely on pre-contractual measures, legal obligations, the exercise of rights, and legitimate interests.'],
['4. Cookies','The website uses a necessary cookie and local storage to remember your cookie-notice preference. Forms load Google reCAPTCHA v2, which may use the technical _GRECAPTCHA cookie for risk analysis. Optional advertising and behavioral analytics cookies are not enabled.'],
['5. Approximate location','After optional cookies are accepted, the form may optionally request an approximate location through the browser. If permission is denied or unavailable, service continues without coordinates.'],
['6. Sharing and technical providers','We use FormSubmit to process and forward messages to InfoService’s institutional email. Forms also use Google reCAPTCHA v2 to reduce automated submissions. The secret key is not exposed in the browser.'],
['7. Security and retention','We use field validation, an anti-spam honeypot, reCAPTCHA v2, FormSubmit’s standard protection and HTTPS. Information is retained as needed for service or applicable legal and contractual periods, then deleted or anonymized where possible.'],
['8. Data subject rights','You may request confirmation, access, correction, anonymization, restriction, deletion, portability where applicable, information about sharing, and review of relevant automated decisions. Requests may require identity verification and referral to the responsible controller.']],dpo:['9. Data Protection Officer (DPO)','For questions and requests about data protection, email ',' with the subject “Privacy and DPO”.','Requests will be answered within applicable legal time limits, subject to security, confidentiality and the possible involvement of another controller.'],closing:'This policy may be updated to reflect legal, technical or operational changes. The current version will always be available on this page.'},
es:{eyebrow:'PRIVACIDAD Y GOBERNANZA',title:'Política de Privacidad',intro:'Información sobre el tratamiento de datos personales en el sitio de InfoService Technology y el contacto del Delegado de Protección de Datos.',updated:'Última actualización: 20 de agosto de 2026.',sections:[
['1. Quién trata los datos','InfoService Technology trata los datos enviados voluntariamente mediante este sitio y sus formularios. En proyectos contratados, la función de responsable o encargado se definirá en el acuerdo aplicable y las instrucciones del cliente.'],
['2. Datos recopilados y finalidades','Podemos recibir nombre, correo, empresa o institución, WhatsApp, asunto y mensaje. Utilizamos estos datos para responder solicitudes, organizar contactos institucionales, informar sobre nuestras soluciones y mantener registros de atención y seguridad.'],
['3. Consentimiento y base legal','Enviar un formulario requiere leer y aceptar esta Política. El consentimiento puede retirarse sin afectar tratamientos anteriores. Según el contexto, también podrán aplicarse medidas precontractuales, obligaciones legales, ejercicio de derechos e intereses legítimos.'],
['4. Cookies','El sitio utiliza una cookie necesaria y almacenamiento local para recordar la preferencia del aviso. Los formularios cargan Google reCAPTCHA v2, que puede usar la cookie técnica _GRECAPTCHA para analizar riesgos. No se activan cookies opcionales de publicidad ni análisis conductual.'],
['5. Ubicación aproximada','Tras aceptar las cookies opcionales, el formulario puede solicitar de forma facultativa una ubicación aproximada mediante el navegador. Si se rechaza o no está disponible, la atención continúa sin coordenadas.'],
['6. Intercambio y proveedores técnicos','Utilizamos FormSubmit para procesar y remitir mensajes al correo institucional de InfoService. Los formularios también usan Google reCAPTCHA v2 para reducir envíos automatizados. La clave secreta no se expone en el navegador.'],
['7. Seguridad y conservación','Aplicamos validación de campos, honeypot antispam, reCAPTCHA v2, protección estándar de FormSubmit y HTTPS. La información se conserva durante la atención o los plazos legales y contractuales aplicables, y después se elimina o anonimiza cuando sea posible.'],
['8. Derechos del titular','El titular puede solicitar confirmación, acceso, rectificación, anonimización, bloqueo, eliminación, portabilidad cuando proceda, información sobre cesiones y revisión de decisiones automatizadas relevantes. La solicitud puede exigir verificación de identidad y remisión al responsable.']],dpo:['9. Delegado de Protección de Datos (DPO)','Para dudas y solicitudes sobre protección de datos, escriba a ',' con el asunto “Privacidad y DPO”.','Las solicitudes se responderán dentro de los plazos legales, respetando la seguridad, la confidencialidad y la posible intervención de otro responsable.'],closing:'Esta política puede actualizarse para reflejar cambios legales, técnicos u operativos. La versión vigente estará siempre disponible en esta página.'},
fr:{eyebrow:'CONFIDENTIALITÉ ET GOUVERNANCE',title:'Politique de confidentialité',intro:'Informations sur le traitement des données personnelles sur le site d’InfoService Technology et le contact du délégué à la protection des données.',updated:'Dernière mise à jour : 20 août 2026.',sections:[
['1. Responsable du traitement','InfoService Technology traite les données transmises volontairement via ce site et ses formulaires. Pour les projets contractuels, le rôle de responsable ou de sous-traitant est défini par l’accord applicable et les instructions du client.'],
['2. Données collectées et finalités','Nous pouvons recevoir votre nom, e-mail, entreprise ou institution, numéro WhatsApp, objet et message. Ces données servent à répondre aux demandes, organiser les contacts institutionnels, informer sur nos solutions et conserver des registres de service et de sécurité.'],
['3. Consentement et base juridique','L’envoi d’un formulaire exige la lecture et l’acceptation de cette Politique. Le consentement peut être retiré sans affecter les traitements antérieurs. Selon le contexte, des mesures précontractuelles, obligations légales, droits et intérêts légitimes peuvent aussi s’appliquer.'],
['4. Cookies','Le site utilise un cookie nécessaire et le stockage local pour mémoriser votre préférence. Les formulaires chargent Google reCAPTCHA v2, qui peut utiliser le cookie technique _GRECAPTCHA pour analyser les risques. Aucun cookie facultatif publicitaire ou d’analyse comportementale n’est activé.'],
['5. Localisation approximative','Après acceptation des cookies facultatifs, le formulaire peut demander une localisation approximative via le navigateur. Si l’autorisation est refusée ou indisponible, le service se poursuit sans coordonnées.'],
['6. Partage et prestataires techniques','Nous utilisons FormSubmit pour traiter et transférer les messages vers l’e-mail institutionnel d’InfoService. Les formulaires utilisent aussi Google reCAPTCHA v2 contre les envois automatisés. La clé secrète n’est pas exposée dans le navigateur.'],
['7. Sécurité et conservation','Nous utilisons la validation des champs, un honeypot antispam, reCAPTCHA v2, la protection standard de FormSubmit et HTTPS. Les informations sont conservées pour le service ou pendant les délais légaux et contractuels, puis supprimées ou anonymisées si possible.'],
['8. Droits des personnes','Vous pouvez demander confirmation, accès, rectification, anonymisation, limitation, effacement, portabilité le cas échéant, information sur les partages et révision des décisions automatisées pertinentes. Une vérification d’identité et un transfert au responsable compétent peuvent être nécessaires.']],dpo:['9. Délégué à la protection des données (DPO)','Pour toute question ou demande concernant les données, écrivez à ',' avec l’objet « Confidentialité et DPO ».','Les demandes seront traitées dans les délais légaux, sous réserve de la sécurité, de la confidentialité et de l’intervention éventuelle d’un autre responsable.'],closing:'Cette politique peut être mise à jour pour refléter des changements juridiques, techniques ou opérationnels. La version en vigueur restera disponible sur cette page.'},
'pt-PT':{eyebrow:'PRIVACIDADE E GOVERNAÇÃO',title:'Política de Privacidade',intro:'Informações sobre o tratamento de dados pessoais no site da InfoService Technology e canal de contacto do Encarregado de Proteção de Dados.',updated:'Última atualização: 20 de agosto de 2026.',sections:[
['1. Quem trata os dados','A InfoService Technology trata os dados enviados voluntariamente através deste site e dos formulários de contacto. Em projetos contratados, o papel de responsável pelo tratamento ou subcontratante será definido no acordo aplicável e nas instruções do cliente.'],
['2. Dados recolhidos e finalidades','Podemos receber nome, e-mail, empresa ou instituição, WhatsApp, assunto e mensagem. Estes dados são utilizados para responder a pedidos, organizar contactos institucionais, prestar informações sobre as soluções e manter registos de atendimento e segurança.'],
['3. Consentimento e fundamento jurídico','O envio do formulário exige a leitura e aceitação desta Política. O consentimento pode ser retirado sem afetar tratamentos anteriores. Conforme o contexto, podem também aplicar-se medidas pré-contratuais, obrigações legais, exercício de direitos e interesses legítimos.'],
['4. Cookies','O site utiliza um cookie necessário e armazenamento local para recordar a preferência do aviso. Os formulários carregam o Google reCAPTCHA v2, que pode utilizar o cookie técnico _GRECAPTCHA para análise de risco. Não são ativados cookies opcionais de publicidade ou análise comportamental.'],
['5. Localização aproximada','Depois de aceitar cookies opcionais, o formulário pode solicitar facultativamente uma localização aproximada através do navegador. Se a autorização for recusada ou indisponível, o atendimento continua sem coordenadas.'],
['6. Partilha e fornecedores técnicos','Utilizamos o FormSubmit para processar e encaminhar mensagens para o e-mail institucional da InfoService. Os formulários também utilizam o Google reCAPTCHA v2 para reduzir envios automatizados. A chave secreta não é exposta no navegador.'],
['7. Segurança e conservação','Aplicamos validação de campos, honeypot antispam, reCAPTCHA v2, proteção padrão do FormSubmit e HTTPS. A informação é conservada durante o atendimento ou pelos prazos legais e contratuais aplicáveis, sendo depois eliminada ou anonimizada quando possível.'],
['8. Direitos do titular','O titular pode solicitar confirmação, acesso, retificação, anonimização, limitação, eliminação, portabilidade quando aplicável, informação sobre partilhas e revisão de decisões automatizadas relevantes. O pedido pode exigir verificação de identidade e encaminhamento para o responsável.']],dpo:['9. Encarregado de Proteção de Dados (DPO)','Para dúvidas e pedidos sobre proteção de dados, envie uma mensagem para ',' com o assunto “Privacidade e DPO”.','Os pedidos serão respondidos dentro dos prazos legais, observando a segurança, a confidencialidade e a eventual atuação de outro responsável.'],closing:'Esta política pode ser atualizada para refletir alterações legais, técnicas ou operacionais. A versão em vigor estará sempre disponível nesta página.'}
};

export default function Privacidade(){const{language}=useLanguage();const c=copies[language];return <Box sx={{py:{xs:8,md:12},bgcolor:'#f8f9fa'}}><Container maxWidth="md"><Typography variant="overline" color="#d81159" fontWeight={800}>{c.eyebrow}</Typography><Typography variant="h1" sx={{mt:2}}>{c.title}</Typography><Typography color="text.secondary" sx={{mt:3,fontSize:17}}>{c.intro}</Typography><Typography variant="body2" color="text.secondary" sx={{mt:2}}>{c.updated}</Typography><Stack spacing={4} sx={{mt:7}}>{c.sections.map(([title,body])=><Box key={title}><Typography variant="h2" sx={{fontSize:{xs:22,md:26},mb:1.25}}>{title}</Typography><Typography color="text.secondary" sx={{lineHeight:1.8}}>{body}</Typography></Box>)}</Stack><Divider sx={{my:6}}/><Box sx={{bgcolor:'#fff',border:'1px solid #e0e0e0',p:{xs:3,md:4}}}><Typography variant="h2" sx={{fontSize:{xs:22,md:26}}}>{c.dpo[0]}</Typography><Typography color="text.secondary" sx={{mt:1.5,lineHeight:1.8}}>{c.dpo[1]}<Link href="mailto:mauroslucios@infoservicetechnology.com.br?subject=Privacidade%20e%20DPO">{email}</Link>{c.dpo[2]}</Typography><Typography color="text.secondary" sx={{mt:1.5,lineHeight:1.8}}>{c.dpo[3]}</Typography></Box><Typography color="text.secondary" sx={{mt:5,lineHeight:1.8}}>{c.closing}</Typography></Container></Box>}
