import {Box,Button,Container,Divider,Stack,Typography} from '@mui/material';
import {Link} from 'react-router-dom';import {usePrivacy} from '../privacy/PrivacyContext';

const Section=({title,children}:{title:string;children:React.ReactNode})=><Box component="section"><Typography variant="h3" sx={{mb:2}}>{title}</Typography><Typography component="div" color="text.secondary" lineHeight={1.8}>{children}</Typography></Box>;
export default function Privacidade(){const{openSettings}=usePrivacy();const dpoName=(import.meta.env.VITE_DPO_NAME as string|undefined)||'Canal de Privacidade da InfoService Technology';return <Box sx={{py:{xs:8,md:12},bgcolor:'#f8f9fa'}}><Container maxWidth="md"><Typography variant="overline" color="#d81159" fontWeight={800}>PRIVACIDADE E DPO</Typography><Typography variant="h1" sx={{mt:2,mb:3}}>Política de Privacidade</Typography><Typography color="text.secondary" fontSize={18} lineHeight={1.75}>Esta política explica como a InfoService Technology trata dados pessoais neste site institucional e como você pode exercer seus direitos.</Typography><Stack spacing={5} divider={<Divider flexItem/>} sx={{mt:7}}>
  <Section title="1. Controlador e canal do encarregado (DPO)"><p>Controlador: InfoService Technology.</p><p>Encarregado/canal informado: <strong>{dpoName}</strong>.</p><p>E-mail para privacidade, proteção de dados e exercício de direitos: <a href="mailto:contato@infoservicetechnology.com.br">contato@infoservicetechnology.com.br</a>.</p></Section>
  <Section title="2. Dados tratados"><p>Podemos tratar nome, e-mail, telefone/WhatsApp, instituição, perfil profissional, assunto e conteúdo da mensagem enviados voluntariamente nos formulários.</p><p>Com consentimento específico, o navegador pode fornecer localização aproximada. Reduzimos a precisão das coordenadas e somente as anexamos a um formulário enviado. Também podem ser processados dados técnicos estritamente necessários, como endereço IP, data, horário, navegador e registros de segurança da hospedagem.</p></Section>
  <Section title="3. Finalidades e bases legais"><p>Usamos os dados para responder contatos, preparar apresentações, conduzir relações institucionais, proteger o site contra abuso e cumprir obrigações legais. O tratamento pode se apoiar em consentimento, procedimentos preliminares relacionados a contrato, legítimo interesse avaliado e cumprimento de obrigação legal, conforme o contexto.</p></Section>
  <Section title="4. Cookies e preferências"><p>Usamos armazenamento necessário para idioma, segurança e registro das suas escolhas. Recursos opcionais somente são ativados de acordo com suas preferências. Você pode revogar ou alterar sua escolha a qualquer momento.</p><Button onClick={openSettings} variant="outlined">Revisar preferências de cookies</Button></Section>
  <Section title="5. Compartilhamento e transferências"><p>Dados podem ser processados por prestadores essenciais de hospedagem, proteção antispam/reCAPTCHA e entrega de formulários, limitados às finalidades contratadas. Alguns fornecedores podem operar infraestrutura fora do Brasil e devem adotar salvaguardas de proteção adequadas.</p></Section>
  <Section title="6. Retenção e segurança"><p>Conservamos os dados pelo tempo necessário ao atendimento, às finalidades informadas e aos prazos legais. Aplicamos minimização, controle de acesso, validação, proteção contra automação e transmissão criptografada. Nenhum sistema, contudo, elimina integralmente todos os riscos.</p></Section>
  <Section title="7. Direitos do titular"><p>Você pode solicitar confirmação de tratamento, acesso, correção, anonimização, bloqueio ou eliminação quando cabível, portabilidade, informação sobre compartilhamentos, revisão de decisões automatizadas e revogação do consentimento. Envie a solicitação ao canal do DPO acima; poderemos confirmar sua identidade para proteger seus dados.</p></Section>
  <Section title="8. Atualizações"><p>Esta política pode ser atualizada para refletir mudanças legais, técnicas ou operacionais. Versão: 19 de agosto de 2026.</p></Section>
  <Box><Button component={Link} to="/contato?assunto=privacidade" variant="contained">Falar com o canal de privacidade</Button></Box>
 </Stack></Container></Box>}
