import {Box,Container,Divider,Link,Stack,Typography} from '@mui/material';

const sections = [
  {title:'1. Quem trata os dados',body:'A InfoService Technology é responsável pelo tratamento dos dados enviados voluntariamente pelos visitantes por meio deste site e dos formulários de contato. Quando atuarmos em um projeto contratado, o papel de controlador ou operador será definido no instrumento aplicável e nas instruções do cliente.'},
  {title:'2. Dados coletados e finalidades',body:'Podemos receber nome, e-mail, empresa ou instituição, WhatsApp, assunto e mensagem. Esses dados são utilizados para responder solicitações, preparar contatos institucionais, prestar informações sobre as soluções e manter registros de atendimento e segurança.'},
  {title:'3. Consentimento e base legal',body:'O envio do formulário depende da confirmação de leitura e aceitação desta Política de Privacidade. O consentimento pode ser revogado pelo titular, sem afetar os tratamentos realizados anteriormente. Dependendo do contexto, também poderão ser aplicadas as bases legais de execução de medidas pré-contratuais, cumprimento de obrigação legal, exercício regular de direitos e legítimo interesse, sempre de forma compatível com a finalidade.'},
  {title:'4. Cookies',body:'O site utiliza um cookie necessário para lembrar a escolha feita no aviso de cookies e o armazenamento local da mesma preferência. Os formulários também carregam o reCAPTCHA v2 do Google, que pode usar o cookie técnico necessário _GRECAPTCHA para análise de risco e proteção contra abuso. Não são ativados cookies opcionais de publicidade ou de análise comportamental por esta implementação. O titular pode apagar os registros diretamente nas configurações do navegador.'},
  {title:'5. Localização aproximada',body:'Somente após a aceitação de cookies opcionais o formulário pode solicitar, de maneira opcional, a localização aproximada pelo recurso de geolocalização do navegador. O site não força a autorização; se ela for recusada ou indisponível, o atendimento continua sem coordenadas. Quando autorizada, a informação é enviada apenas como referência aproximada junto ao contato.'},
  {title:'6. Compartilhamento e fornecedores técnicos',body:'Para receber e encaminhar as mensagens, utilizamos o FormSubmit, serviço de processamento de formulários. Os dados enviados são transmitidos ao endpoint do serviço e encaminhados ao e-mail institucional da InfoService. Os formulários também utilizam o Google reCAPTCHA v2 no modo checkbox “Não sou um robô” para reduzir envios automatizados. O token temporário da validação acompanha a requisição do formulário; a chave secreta não é exposta no navegador.'},
  {title:'7. Segurança e retenção',body:'Aplicamos medidas técnicas compatíveis com o porte e a finalidade do atendimento, incluindo validações de campos, honeypot anti-spam, reCAPTCHA v2, proteção padrão do FormSubmit e transmissão HTTPS. As informações são mantidas pelo tempo necessário para responder e documentar o atendimento, ou pelos prazos legais e contratuais aplicáveis, após o que serão eliminadas ou anonimizadas quando possível.'},
  {title:'8. Direitos do titular',body:'Nos termos da legislação aplicável, o titular pode solicitar confirmação de tratamento, acesso, correção, anonimização, bloqueio, eliminação, portabilidade quando cabível, informação sobre compartilhamentos e revisão das decisões automatizadas que produzam efeitos relevantes. A solicitação será analisada e poderá exigir confirmação de identidade e, quando houver cliente controlador, encaminhamento ao controlador responsável.'},
];

export default function Privacidade(){return <Box sx={{py:{xs:8,md:12},bgcolor:'#f8f9fa'}}><Container maxWidth="md"><Typography variant="overline" color="#d81159" fontWeight={800}>PRIVACIDADE E GOVERNANÇA</Typography><Typography variant="h1" sx={{mt:2}}>Política de Privacidade</Typography><Typography color="text.secondary" sx={{mt:3,fontSize:17}}>Informações sobre o tratamento de dados pessoais no site da InfoService Technology e canal de atendimento do Encarregado.</Typography><Typography variant="body2" color="text.secondary" sx={{mt:2}}>Última atualização: 20 de agosto de 2026.</Typography><Stack spacing={4} sx={{mt:7}}>{sections.map(section=><Box key={section.title}><Typography variant="h2" sx={{fontSize:{xs:22,md:26},mb:1.25}}>{section.title}</Typography><Typography color="text.secondary" sx={{lineHeight:1.8}}>{section.body}</Typography></Box>)}</Stack><Divider sx={{my:6}}/><Box sx={{bgcolor:'#fff',border:'1px solid #e0e0e0',p:{xs:3,md:4}}}><Typography variant="h2" sx={{fontSize:{xs:22,md:26}}}>9. Encarregado pelo tratamento de dados (DPO)</Typography><Typography color="text.secondary" sx={{mt:1.5,lineHeight:1.8}}>O canal de privacidade da InfoService recebe dúvidas, solicitações e comunicações relacionadas à proteção de dados pessoais. Para falar com o DPO/Encarregado, envie uma mensagem para <Link href="mailto:mauroslucios@infoservicetechnology.com.br?subject=Privacidade%20e%20DPO">mauroslucios@infoservicetechnology.com.br</Link> com o assunto “Privacidade e DPO”.</Typography><Typography color="text.secondary" sx={{mt:1.5,lineHeight:1.8}}>As solicitações serão respondidas dentro dos prazos legais aplicáveis, observados os limites de segurança, sigilo e a eventual atuação de outro controlador responsável pela origem dos dados.</Typography></Box><Typography color="text.secondary" sx={{mt:5,lineHeight:1.8}}>Esta política pode ser atualizada para refletir mudanças legais, técnicas ou operacionais. A versão vigente estará sempre disponível nesta página.</Typography></Container></Box>}
