import {Box,Container,Divider,Link,Stack,Typography} from '@mui/material';

const sections=[
  {title:'1. Finalidade e aceitação',body:'Estes Termos regulam o acesso e o uso do site institucional da InfoService Technology. Ao navegar neste site ou utilizar seus formulários, você declara ter lido e compreendido estas condições. Serviços, provas de conceito, plataformas e projetos contratados poderão possuir instrumentos específicos, que prevalecerão em caso de conflito.'},
  {title:'2. Conteúdo institucional',body:'As informações apresentadas possuem finalidade institucional e informativa. Elas não constituem recomendação médica, diagnóstico, orientação clínica, parecer jurídico ou garantia de resultado. Demonstrações, ilustrações, indicadores e descrições de funcionalidades podem representar cenários conceituais ou ambientes em evolução.'},
  {title:'3. Uso permitido',body:'Você pode consultar e compartilhar links públicos deste site para fins legítimos. É proibido tentar acessar áreas restritas sem autorização, interferir no funcionamento ou na segurança, introduzir código malicioso, utilizar automação abusiva, coletar dados indevidamente ou empregar o conteúdo para prática ilícita ou que viole direitos de terceiros.'},
  {title:'4. Propriedade intelectual',body:'Marcas, identidade visual, textos, imagens, interfaces, arquiteturas, materiais técnicos e demais conteúdos são protegidos pela legislação aplicável e pertencem à InfoService Technology ou a seus legítimos licenciadores. Nenhuma licença ou cessão é concedida além da visualização e do uso normal deste site.'},
  {title:'5. Links, integrações e disponibilidade',body:'O site pode mencionar serviços, padrões ou páginas de terceiros. A InfoService não controla nem endossa automaticamente seus conteúdos, políticas ou disponibilidade. Podemos atualizar, suspender ou alterar partes do site para manutenção, segurança ou evolução institucional, sem garantia de funcionamento ininterrupto.'},
  {title:'6. Dados pessoais e formulários',body:'O tratamento de dados pessoais enviados por formulários, preferências de cookies e demais interações está descrito na Política de Privacidade. O usuário é responsável pela veracidade das informações fornecidas e não deve enviar dados pessoais sensíveis ou informações clínicas pelos formulários institucionais, salvo quando houver canal e orientação específicos.'},
  {title:'7. Responsabilidades',body:'Empregamos esforços razoáveis para manter informações e recursos seguros e atualizados. Na extensão permitida pela lei, não nos responsabilizamos por decisões tomadas exclusivamente com base em conteúdo institucional, por indisponibilidades externas, uso incompatível com estes Termos ou danos decorrentes de ações de terceiros fora de nosso controle.'},
  {title:'8. Alterações e legislação aplicável',body:'Estes Termos podem ser atualizados para refletir mudanças legais, técnicas ou operacionais. A versão vigente e sua data de atualização permanecerão disponíveis nesta página. Aplicam-se as leis da República Federativa do Brasil, preservados os direitos e foros obrigatórios previstos na legislação.'},
];

export default function TermosDeUso(){return <Box sx={{py:{xs:8,md:12},bgcolor:'#f8f9fa'}}><Container maxWidth="md"><Typography variant="overline" color="#d81159" fontWeight={800}>REGRAS E DIRETRIZES</Typography><Typography variant="h1" sx={{mt:2}}>Termos de Uso</Typography><Typography color="text.secondary" sx={{mt:3,fontSize:17}}>Condições para acesso e utilização do site institucional da InfoService Technology.</Typography><Typography variant="body2" color="text.secondary" sx={{mt:2}}>Última atualização: 25 de agosto de 2026.</Typography><Stack spacing={4} sx={{mt:7}}>{sections.map(section=><Box key={section.title}><Typography variant="h2" sx={{fontSize:{xs:22,md:26},mb:1.25}}>{section.title}</Typography><Typography color="text.secondary" sx={{lineHeight:1.8}}>{section.body}</Typography></Box>)}</Stack><Divider sx={{my:6}}/><Box sx={{bgcolor:'#fff',border:'1px solid #e0e0e0',p:{xs:3,md:4}}}><Typography variant="h2" sx={{fontSize:{xs:22,md:26}}}>9. Contato</Typography><Typography color="text.secondary" sx={{mt:1.5,lineHeight:1.8}}>Em caso de dúvida sobre estes Termos, entre em contato pelo e-mail <Link href="mailto:contato@infoservicetechnology.com.br?subject=Termos%20de%20Uso">contato@infoservicetechnology.com.br</Link>. Para assuntos relacionados a dados pessoais, consulte também nossa <Link href="/privacidade">Política de Privacidade</Link>.</Typography></Box></Container></Box>}
