/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as EcossistemaRouteImport } from './routes/ecossistema'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesRedesHospitalaresRouteImport } from './routes/solucoes.redes-hospitalares'
import { Route as SolucoesInteligenciaEpidemiologicaRouteImport } from './routes/solucoes.inteligencia-epidemiologica'
import { Route as SolucoesGestoresPublicosRouteImport } from './routes/solucoes.gestores-publicos'

const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const EcossistemaRoute = EcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRedesHospitalaresRoute =
  SolucoesRedesHospitalaresRouteImport.update({
    id: '/solucoes/redes-hospitalares',
    path: '/solucoes/redes-hospitalares',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesInteligenciaEpidemiologicaRoute =
  SolucoesInteligenciaEpidemiologicaRouteImport.update({
    id: '/solucoes/inteligencia-epidemiologica',
    path: '/solucoes/inteligencia-epidemiologica',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesGestoresPublicosRoute =
  SolucoesGestoresPublicosRouteImport.update({
    id: '/solucoes/gestores-publicos',
    path: '/solucoes/gestores-publicos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/ecossistema': typeof EcossistemaRoute
  '/governanca': typeof GovernancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnologia': typeof TecnologiaRoute
  '/solucoes/gestores-publicos': typeof SolucoesGestoresPublicosRoute
  '/solucoes/inteligencia-epidemiologica': typeof SolucoesInteligenciaEpidemiologicaRoute
  '/solucoes/redes-hospitalares': typeof SolucoesRedesHospitalaresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/ecossistema': typeof EcossistemaRoute
  '/governanca': typeof GovernancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnologia': typeof TecnologiaRoute
  '/solucoes/gestores-publicos': typeof SolucoesGestoresPublicosRoute
  '/solucoes/inteligencia-epidemiologica': typeof SolucoesInteligenciaEpidemiologicaRoute
  '/solucoes/redes-hospitalares': typeof SolucoesRedesHospitalaresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/ecossistema': typeof EcossistemaRoute
  '/governanca': typeof GovernancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnologia': typeof TecnologiaRoute
  '/solucoes/gestores-publicos': typeof SolucoesGestoresPublicosRoute
  '/solucoes/inteligencia-epidemiologica': typeof SolucoesInteligenciaEpidemiologicaRoute
  '/solucoes/redes-hospitalares': typeof SolucoesRedesHospitalaresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/ecossistema'
    | '/governanca'
    | '/sitemap.xml'
    | '/tecnologia'
    | '/solucoes/gestores-publicos'
    | '/solucoes/inteligencia-epidemiologica'
    | '/solucoes/redes-hospitalares'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/ecossistema'
    | '/governanca'
    | '/sitemap.xml'
    | '/tecnologia'
    | '/solucoes/gestores-publicos'
    | '/solucoes/inteligencia-epidemiologica'
    | '/solucoes/redes-hospitalares'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/ecossistema'
    | '/governanca'
    | '/sitemap.xml'
    | '/tecnologia'
    | '/solucoes/gestores-publicos'
    | '/solucoes/inteligencia-epidemiologica'
    | '/solucoes/redes-hospitalares'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  EcossistemaRoute: typeof EcossistemaRoute
  GovernancaRoute: typeof GovernancaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TecnologiaRoute: typeof TecnologiaRoute
  SolucoesGestoresPublicosRoute: typeof SolucoesGestoresPublicosRoute
  SolucoesInteligenciaEpidemiologicaRoute: typeof SolucoesInteligenciaEpidemiologicaRoute
  SolucoesRedesHospitalaresRoute: typeof SolucoesRedesHospitalaresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecossistema': {
      id: '/ecossistema'
      path: '/ecossistema'
      fullPath: '/ecossistema'
      preLoaderRoute: typeof EcossistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/redes-hospitalares': {
      id: '/solucoes/redes-hospitalares'
      path: '/solucoes/redes-hospitalares'
      fullPath: '/solucoes/redes-hospitalares'
      preLoaderRoute: typeof SolucoesRedesHospitalaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/inteligencia-epidemiologica': {
      id: '/solucoes/inteligencia-epidemiologica'
      path: '/solucoes/inteligencia-epidemiologica'
      fullPath: '/solucoes/inteligencia-epidemiologica'
      preLoaderRoute: typeof SolucoesInteligenciaEpidemiologicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/gestores-publicos': {
      id: '/solucoes/gestores-publicos'
      path: '/solucoes/gestores-publicos'
      fullPath: '/solucoes/gestores-publicos'
      preLoaderRoute: typeof SolucoesGestoresPublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  EcossistemaRoute: EcossistemaRoute,
  GovernancaRoute: GovernancaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TecnologiaRoute: TecnologiaRoute,
  SolucoesGestoresPublicosRoute: SolucoesGestoresPublicosRoute,
  SolucoesInteligenciaEpidemiologicaRoute:
    SolucoesInteligenciaEpidemiologicaRoute,
  SolucoesRedesHospitalaresRoute: SolucoesRedesHospitalaresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
