/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermoDeUsoRouteImport } from './routes/termo-de-uso'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaDeSegurancaRouteImport } from './routes/politica-de-seguranca'
import { Route as PoliticaRouteImport } from './routes/politica'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as EcossistemaRouteImport } from './routes/ecossistema'
import { Route as DpoRouteImport } from './routes/dpo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolucoesRedesHospitalaresRouteImport } from './routes/solucoes.redes-hospitalares'
import { Route as SolucoesInteligenciaEpidemiologicaRouteImport } from './routes/solucoes.inteligencia-epidemiologica'
import { Route as SolucoesGestoresPublicosRouteImport } from './routes/solucoes.gestores-publicos'
import { Route as BlogPredicaoDeDoencasRouteImport } from './routes/blog.predicao-de-doencas'
import { Route as BlogParceriasEstrategicasRouteImport } from './routes/blog.parcerias-estrategicas'
import { Route as BlogModelosPreditivosRouteImport } from './routes/blog.modelos-preditivos'

const TermoDeUsoRoute = TermoDeUsoRouteImport.update({
  id: '/termo-de-uso',
  path: '/termo-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeSegurancaRoute = PoliticaDeSegurancaRouteImport.update({
  id: '/politica-de-seguranca',
  path: '/politica-de-seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaRoute = PoliticaRouteImport.update({
  id: '/politica',
  path: '/politica',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const EcossistemaRoute = EcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => rootRouteImport,
} as any)
const DpoRoute = DpoRouteImport.update({
  id: '/dpo',
  path: '/dpo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRedesHospitalaresRoute =
  SolucoesRedesHospitalaresRouteImport.update({
    id: '/solucoes/redes-hospitalares',
    path: '/solucoes/redes-hospitalares',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesInteligenciaEpidemiologicaRoute =
  SolucoesInteligenciaEpidemiologicaRouteImport.update({
    id: '/solucoes/inteligencia-epidemiologica',
    path: '/solucoes/inteligencia-epidemiologica',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesGestoresPublicosRoute =
  SolucoesGestoresPublicosRouteImport.update({
    id: '/solucoes/gestores-publicos',
    path: '/solucoes/gestores-publicos',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPredicaoDeDoencasRoute = BlogPredicaoDeDoencasRouteImport.update({
  id: '/blog/predicao-de-doencas',
  path: '/blog/predicao-de-doencas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogParceriasEstrategicasRoute =
  BlogParceriasEstrategicasRouteImport.update({
    id: '/blog/parcerias-estrategicas',
    path: '/blog/parcerias-estrategicas',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogModelosPreditivosRoute = BlogModelosPreditivosRouteImport.update({
  id: '/blog/modelos-preditivos',
  path: '/blog/modelos-preditivos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dpo': typeof DpoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/governanca': typeof GovernancaRoute
  '/politica': typeof PoliticaRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnologia': typeof TecnologiaRoute
  '/termo-de-uso': typeof TermoDeUsoRoute
  '/blog/modelos-preditivos': typeof BlogModelosPreditivosRoute
  '/blog/parcerias-estrategicas': typeof BlogParceriasEstrategicasRoute
  '/blog/predicao-de-doencas': typeof BlogPredicaoDeDoencasRoute
  '/solucoes/gestores-publicos': typeof SolucoesGestoresPublicosRoute
  '/solucoes/inteligencia-epidemiologica': typeof SolucoesInteligenciaEpidemiologicaRoute
  '/solucoes/redes-hospitalares': typeof SolucoesRedesHospitalaresRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dpo': typeof DpoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/governanca': typeof GovernancaRoute
  '/politica': typeof PoliticaRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnologia': typeof TecnologiaRoute
  '/termo-de-uso': typeof TermoDeUsoRoute
  '/blog/modelos-preditivos': typeof BlogModelosPreditivosRoute
  '/blog/parcerias-estrategicas': typeof BlogParceriasEstrategicasRoute
  '/blog/predicao-de-doencas': typeof BlogPredicaoDeDoencasRoute
  '/solucoes/gestores-publicos': typeof SolucoesGestoresPublicosRoute
  '/solucoes/inteligencia-epidemiologica': typeof SolucoesInteligenciaEpidemiologicaRoute
  '/solucoes/redes-hospitalares': typeof SolucoesRedesHospitalaresRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dpo': typeof DpoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/governanca': typeof GovernancaRoute
  '/politica': typeof PoliticaRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnologia': typeof TecnologiaRoute
  '/termo-de-uso': typeof TermoDeUsoRoute
  '/blog/modelos-preditivos': typeof BlogModelosPreditivosRoute
  '/blog/parcerias-estrategicas': typeof BlogParceriasEstrategicasRoute
  '/blog/predicao-de-doencas': typeof BlogPredicaoDeDoencasRoute
  '/solucoes/gestores-publicos': typeof SolucoesGestoresPublicosRoute
  '/solucoes/inteligencia-epidemiologica': typeof SolucoesInteligenciaEpidemiologicaRoute
  '/solucoes/redes-hospitalares': typeof SolucoesRedesHospitalaresRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dpo'
    | '/ecossistema'
    | '/governanca'
    | '/politica'
    | '/politica-de-seguranca'
    | '/sitemap.xml'
    | '/tecnologia'
    | '/termo-de-uso'
    | '/blog/modelos-preditivos'
    | '/blog/parcerias-estrategicas'
    | '/blog/predicao-de-doencas'
    | '/solucoes/gestores-publicos'
    | '/solucoes/inteligencia-epidemiologica'
    | '/solucoes/redes-hospitalares'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dpo'
    | '/ecossistema'
    | '/governanca'
    | '/politica'
    | '/politica-de-seguranca'
    | '/sitemap.xml'
    | '/tecnologia'
    | '/termo-de-uso'
    | '/blog/modelos-preditivos'
    | '/blog/parcerias-estrategicas'
    | '/blog/predicao-de-doencas'
    | '/solucoes/gestores-publicos'
    | '/solucoes/inteligencia-epidemiologica'
    | '/solucoes/redes-hospitalares'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/dpo'
    | '/ecossistema'
    | '/governanca'
    | '/politica'
    | '/politica-de-seguranca'
    | '/sitemap.xml'
    | '/tecnologia'
    | '/termo-de-uso'
    | '/blog/modelos-preditivos'
    | '/blog/parcerias-estrategicas'
    | '/blog/predicao-de-doencas'
    | '/solucoes/gestores-publicos'
    | '/solucoes/inteligencia-epidemiologica'
    | '/solucoes/redes-hospitalares'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DpoRoute: typeof DpoRoute
  EcossistemaRoute: typeof EcossistemaRoute
  GovernancaRoute: typeof GovernancaRoute
  PoliticaRoute: typeof PoliticaRoute
  PoliticaDeSegurancaRoute: typeof PoliticaDeSegurancaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TecnologiaRoute: typeof TecnologiaRoute
  TermoDeUsoRoute: typeof TermoDeUsoRoute
  BlogModelosPreditivosRoute: typeof BlogModelosPreditivosRoute
  BlogParceriasEstrategicasRoute: typeof BlogParceriasEstrategicasRoute
  BlogPredicaoDeDoencasRoute: typeof BlogPredicaoDeDoencasRoute
  SolucoesGestoresPublicosRoute: typeof SolucoesGestoresPublicosRoute
  SolucoesInteligenciaEpidemiologicaRoute: typeof SolucoesInteligenciaEpidemiologicaRoute
  SolucoesRedesHospitalaresRoute: typeof SolucoesRedesHospitalaresRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termo-de-uso': {
      id: '/termo-de-uso'
      path: '/termo-de-uso'
      fullPath: '/termo-de-uso'
      preLoaderRoute: typeof TermoDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-seguranca': {
      id: '/politica-de-seguranca'
      path: '/politica-de-seguranca'
      fullPath: '/politica-de-seguranca'
      preLoaderRoute: typeof PoliticaDeSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica': {
      id: '/politica'
      path: '/politica'
      fullPath: '/politica'
      preLoaderRoute: typeof PoliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecossistema': {
      id: '/ecossistema'
      path: '/ecossistema'
      fullPath: '/ecossistema'
      preLoaderRoute: typeof EcossistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpo': {
      id: '/dpo'
      path: '/dpo'
      fullPath: '/dpo'
      preLoaderRoute: typeof DpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/redes-hospitalares': {
      id: '/solucoes/redes-hospitalares'
      path: '/solucoes/redes-hospitalares'
      fullPath: '/solucoes/redes-hospitalares'
      preLoaderRoute: typeof SolucoesRedesHospitalaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/inteligencia-epidemiologica': {
      id: '/solucoes/inteligencia-epidemiologica'
      path: '/solucoes/inteligencia-epidemiologica'
      fullPath: '/solucoes/inteligencia-epidemiologica'
      preLoaderRoute: typeof SolucoesInteligenciaEpidemiologicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/gestores-publicos': {
      id: '/solucoes/gestores-publicos'
      path: '/solucoes/gestores-publicos'
      fullPath: '/solucoes/gestores-publicos'
      preLoaderRoute: typeof SolucoesGestoresPublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/predicao-de-doencas': {
      id: '/blog/predicao-de-doencas'
      path: '/blog/predicao-de-doencas'
      fullPath: '/blog/predicao-de-doencas'
      preLoaderRoute: typeof BlogPredicaoDeDoencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/parcerias-estrategicas': {
      id: '/blog/parcerias-estrategicas'
      path: '/blog/parcerias-estrategicas'
      fullPath: '/blog/parcerias-estrategicas'
      preLoaderRoute: typeof BlogParceriasEstrategicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/modelos-preditivos': {
      id: '/blog/modelos-preditivos'
      path: '/blog/modelos-preditivos'
      fullPath: '/blog/modelos-preditivos'
      preLoaderRoute: typeof BlogModelosPreditivosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DpoRoute: DpoRoute,
  EcossistemaRoute: EcossistemaRoute,
  GovernancaRoute: GovernancaRoute,
  PoliticaRoute: PoliticaRoute,
  PoliticaDeSegurancaRoute: PoliticaDeSegurancaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TecnologiaRoute: TecnologiaRoute,
  TermoDeUsoRoute: TermoDeUsoRoute,
  BlogModelosPreditivosRoute: BlogModelosPreditivosRoute,
  BlogParceriasEstrategicasRoute: BlogParceriasEstrategicasRoute,
  BlogPredicaoDeDoencasRoute: BlogPredicaoDeDoencasRoute,
  SolucoesGestoresPublicosRoute: SolucoesGestoresPublicosRoute,
  SolucoesInteligenciaEpidemiologicaRoute:
    SolucoesInteligenciaEpidemiologicaRoute,
  SolucoesRedesHospitalaresRoute: SolucoesRedesHospitalaresRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
